version: '2'
services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://garden@postgres/todos
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: garden
      POSTGRES_DB: garden
    